import styles from "../page.module.css";
import Link from "next/link" 
import type { Metadata } from "next";

async function getData() {
    const response = await fetch('https://jsonplaceholder.typicode.com/posts')
    return response.json()

}
export const metadata: Metadata = {
    title: "Blog| Next App",
    description: "Generated by create next app",
  };
 

  export default async function Blog () {
    const posts = await getData();
    return (
        <main className={styles.main}>
       <h1>Blog page</h1>
       <ul>
        {posts.map((post:any)=>(
            <li key = {post.id}>
                <Link href={`/blog/${post.id}`}>{post.title}</Link>
            </li>
        ))}
       </ul>
        </main>
    )
}

